name    'snow_xclient'
version '0.1.0'
author 'syluts'
license 'FFA License'
summary 'Module for installing xclient.*.rpm'
description 'Module for installing xclient.*.rpm / SNOW project'
#project_page 'https://github.com/elasticsearch/puppet-logstashforwarder'
#dependency 'puppetlabs/stdlib', '>= 3.0.0'

